site_name: djinni-support-lib
markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - admonition
theme:
  name: material
nav:
  - install.md
  - python-support.md
  - developer-guide.md
